version: '2.1'

volumes:
   geoserver-data:

services:
   layman:
      container_name: layman
      build: .
      image: layman:latest
      command: flask run --host=0.0.0.0 --port=8000
      env_file:
         - .env
      ports:
        - 8000:8000
      volumes:
        - ./src:/code/src
