name: Version

on: [push]

jobs:
  Version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v1

    - name: Echo variables
      run: |
        echo "Commit SHA: ${GITHUB_SHA}"
        echo "Whole ref: ${GITHUB_REF}"
        branch=${GITHUB_REF#refs/heads/}
        tag=${GITHUB_REF#refs/tags/}
        echo "branch: ${branch}"
        echo "tag: ${tag}"
        echo "${GITHUB_REF}"
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
