name: Version

on: [push]

jobs:
  Version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v1


    - name: Echo variables
      run: |
        branch=${GITHUB_REF#refs/heads/}
        tag=${GITHUB_REF#refs/tags/}
        echo "Commit SHA: ${GITHUB_SHA}"
        echo "Whole ref: ${GITHUB_REF}"
        echo "branch: ${branch}"
        echo "tag: ${tag}"
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

        echo "Commit SHA: ${GITHUB_SHA}" > version.txt
        echo "Whole ref: ${GITHUB_REF}" >> version.txt
        echo "branch: ${branch}" >> version.txt
        echo "tag: ${tag}" >> version.txt
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}' >> version.txt

    - name: Direct echo
      run: |
        git config --local user.email "auto_action@github"
        git config --local user.name "AUTOMAT"
        git describe >> version.txt
        git describe --tag >> version.txt

    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: version.txt
        path: version.txt

    - name: Commit and push
      run: |
        git config --local user.email "auto_action@github"
        git config --local user.name "AUTOMAT"
        git commit -a --amend --no-edit
        git push --force
