name: Version

on: [push]

jobs:
  Version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find Tag
      id: tagger
      uses: jimschubert/query-tag-action@v1

    - name: Find Tag
      id: tagger_head
      uses: jimschubert/query-tag-action@v1
      with:
        commit-ish: "HEAD"

    - name: Find Tag
      id: tagger_head2
      uses: jimschubert/query-tag-action@v1
      with:
        commit-ish: "HEAD^"

    - name: Find Tag
      id: tagger_empty
      uses: jimschubert/query-tag-action@v1
      with:
        commit-ish: ""

    - name: Echo variables
      run: |
        echo "Commit SHA: ${GITHUB_SHA}"
        echo "Whole ref: ${GITHUB_REF}"
        branch=${GITHUB_REF#refs/heads/}
        echo "branch: ${branch}"
        echo "${GITHUB_REF}"
        echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
        echo 'Output from Find Tag: ${{steps.tagger_head.outputs.tag}}'
        echo 'Output from Find Tag: ${{steps.tagger_head2.outputs.tag}}'
        echo 'Output from Find Tag: ${{steps.tagger_empty.outputs.tag}}'
