name: Version

on: [push]

jobs:
  Version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo variables
        run: |
          echo ${GITHUB_SHA}
          branch=${GITHUB_REF#refs/heads/}
          echo "branch: ${branch}"
          echo "::set-output name=secret_name::${branch^^}"
          echo "secret: ${{ secrets['MASTER'] }}"
      - name: Read Secret
        id: read_secret
        shell: bash
        env:
          SECRET_NAME: ${{ steps.environment.output.secret_name }}
          SECRET: ${{ secrets[steps.environment.output.secret_name] }}
        run: |
          echo "SECRET_NAME: ${SECRET_NAME}"
          echo "SECRET: ${SECRET}"
